name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  DockerImage_CI:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run test
      run: |
        pytest

  DockerImage_CD:
    needs: DockerImage_CI
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: login docker repo
      uses: docker/login-action@v3
      with:
        # set secrets variabiles in Github:
        #   SettingS -->  Security --> Securites and variables --> Action --> Repository secrets
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and publish Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./DockerFile     # Only need it, when the name != "Dockerfile"
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/flask-app:latest

    - name: Image digest
      run: echo ${{steps.Docker_CD.ouputs.digest}}
